# Use controls group runners unless overrriden in jobs
default:
  tags:
    - controls

stages:
  - test
  - build-apps
  - build-images

.node_test:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run all-checks
    - npm run test

# Default job to build images
.build_images:
  stage: build-images
  script:
    - mkdir machine-status
    - mv build/ machine-status/
    - ls -al machine-status
    - echo "Building image..."
    - env | grep "CI_"
    - /bin/sh ./kanikobuild.sh
    - echo "Done"

node 16:
  extends: .node_test
  image: node:16

build screen app:
  stage: build-apps
  image: node:16
  script:
    - npm ci
    # Environment variables are captured at build time.
    - export REACT_APP_CONIQL_SOCKET=coniql.diamond.ac.uk:443
    - export REACT_APP_CONIQL_SSL=true
    - export REACT_APP_VERSION=$CI_UPSTREAM_TAG
    - export REACT_APP_BUILD_TIME=$(date --iso=minutes)
    - export REACT_APP_BASE_URL=machine-status-screen.diamond.ac.uk
    - export REACT_APP_PAGE_DISPLAY_TIME_SEC=15
    - export REACT_APP_BUILD_TARGET=screen
    - npm run build
  artifacts:
    paths:
      - build/

build public app:
  stage: build-apps
  image: node:16
  script:
    - npm ci
    # Environment variables are captured at build time.
    - export REACT_APP_CONIQL_SOCKET=coniql-public.diamond.ac.uk:443
    - export REACT_APP_CONIQL_SSL=true
    - export REACT_APP_VERSION=$CI_UPSTREAM_TAG
    - export REACT_APP_BUILD_TIME=$(date --iso=minutes)
    - export REACT_APP_BASE_URL=machine-status.diamond.ac.uk
    - export REACT_APP_PAGE_DISPLAY_TIME_SEC=15
    - export REACT_APP_BUILD_TARGET=public
    - npm run build
  artifacts:
    paths:
      - build/

# Build and release images to registry

build screen image:
  extends: .build_images
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [""]
  before_script:
    - export APP_VERSION=screen
  dependencies:
    - build screen app

build public image:
  extends: .build_images
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [""]
  before_script:
    - export APP_VERSION=screen
  dependencies:
    - build public app
