# Use controls group runners unless overrriden in jobs
default:
  tags:
    - controls

stages:
  - build-screen-app
  - build-internal-app

build-screen-app:
  stage: build-screen-app
  image: node:16
  script:
    - npm ci
    # Environment variables are captured at build time.
    - export REACT_APP_CONIQL_SOCKET=coniql.diamond.ac.uk:443
    - export REACT_APP_CONIQL_SSL=true
    - export REACT_APP_VERSION=$CI_UPSTREAM_TAG
    - export REACT_APP_BUILD_TIME=$(date --iso=minutes)
    - export REACT_APP_BASE_URL=machine-status-screen.diamond.ac.uk
    - export REACT_APP_PAGE_DISPLAY_TIME_SEC=15
    - export REACT_APP_BUILD_TARGET=display
    - npm run build
  artifacts:
    paths:
      - build/

build-internal-app:
  stage: build-internal-app
  image: node:16
  script:
    - npm ci
    # Environment variables are captured at build time.
    - export REACT_APP_CONIQL_SOCKET=coniql.diamond.ac.uk:443
    - export REACT_APP_CONIQL_SSL=true
    - export REACT_APP_VERSION=$CI_UPSTREAM_TAG
    - export REACT_APP_BUILD_TIME=$(date --iso=minutes)
    - export REACT_APP_BASE_URL=machine-status-screen.diamond.ac.uk
    - export REACT_APP_PAGE_DISPLAY_TIME_SEC=15
    - export REACT_APP_BUILD_TARGET=web
    - npm run build
  artifacts:
    paths:
      - build/
